'use client';
import { useEffect, useState } from 'react';
import type { HistoryMode, MonthlyFinancialPoint } from '@/lib/financialHistory';
import { formatCurrency } from '@/lib/formatters';
export default function FinancialHistoryChart({rows,mode='cashFlow',label,onInspect}:{rows:MonthlyFinancialPoint[];mode?:HistoryMode;label:string;onInspect?:(row:MonthlyFinancialPoint|null)=>void}){
 const [selected,setSelected]=useState<number|null>(null);useEffect(()=>{setSelected(null);onInspect?.(null)},[rows,mode,onInspect]);
 const width=820,height=220,pad={left:0,right:0,top:28,bottom:12},innerWidth=width;
 const incomeValues=rows.map(r=>r.income),expenseValues=rows.map(r=>mode==='cashFlow'?r.cashExpenses:r.operatingExpenses),extent=Math.max(1,...incomeValues,...expenseValues);
 const zeroY=height*.48,positiveHeight=zeroY-pad.top,negativeHeight=height-pad.bottom-zeroY,xStep=innerWidth/Math.max(1,rows.length),barWidth=Math.min(28,Math.max(10,xStep*.32));
 const x=(i:number)=>xStep*(i+.5),incomeY=(v:number)=>zeroY-(v/extent)*positiveHeight,expenseH=(v:number)=>(v/extent)*negativeHeight,active=selected==null?null:rows[selected];
 function inspect(e:React.PointerEvent<SVGSVGElement>){if(!rows.length)return;const rect=e.currentTarget.getBoundingClientRect(),pointer=(e.clientX-rect.left)/rect.width*width,index=Math.max(0,Math.min(rows.length-1,Math.floor(pointer/Math.max(1,xStep))));setSelected(index);onInspect?.(rows[index])}function finish(){setSelected(null);onInspect?.(null)}
 return <div className="financial-history-chart-wrap"><div className="financial-history-plot"><svg className="financial-history-chart" viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none" role="img" aria-label={label} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);inspect(e)}} onPointerMove={e=>{if(e.pointerType==='mouse'||e.currentTarget.hasPointerCapture(e.pointerId))inspect(e)}} onPointerUp={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);finish()}} onPointerLeave={e=>{if(e.pointerType==='mouse')finish()}} onPointerCancel={finish}><line x1="0" x2={width} y1={zeroY} y2={zeroY} className="financial-history-zero" vectorEffect="non-scaling-stroke"/>{rows.map((r,i)=><g key={r.key}><rect x={x(i)-barWidth/2} y={incomeY(incomeValues[i])} width={barWidth} height={zeroY-incomeY(incomeValues[i])} rx="4" className="financial-history-income-bar"/><rect x={x(i)-barWidth/2} y={zeroY} width={barWidth} height={expenseH(expenseValues[i])} rx="4" className="financial-history-expense-bar"/></g>)}{selected!=null&&<line x1={x(selected)} x2={x(selected)} y1={pad.top} y2={height-pad.bottom} className="financial-history-guide" vectorEffect="non-scaling-stroke"/>}<rect x="0" y="0" width={width} height={height} className="financial-history-hit"/></svg>{active&&<div className="financial-history-tooltip" data-edge={selected===0?'left':selected===rows.length-1?'right':'center'} style={{left:`${(x(selected!)/width)*100}%`}}><strong>{active.fullLabel}</strong><b>{formatCurrency(active.cashFlow)}</b><span><i>Income</i><em>{formatCurrency(active.income)}</em></span><span><i>Expenses</i><em>{formatCurrency(mode==='cashFlow'?active.cashExpenses:active.operatingExpenses)}</em></span></div>}</div><div className="financial-history-axis" style={{gridTemplateColumns:`repeat(${Math.max(1,rows.length)},minmax(0,1fr))`}} aria-hidden="true">{rows.map(r=><span key={r.key}>{r.label}</span>)}</div></div>;
}
