'use client';
import { useMemo,useState } from 'react';
import { categoryKey } from '@/lib/accounting';
import { formatCurrency } from '@/lib/formatters';
type Tx={transaction_date:string;type:string;category:string;amount:number;status?:string|null};
type View='quarterly'|'annual';
export default function PropertyExpenseTrendsChart({transactions}:{transactions:Tx[]}){
 const [view,setView]=useState<View>('quarterly'),[selectedKey,setSelectedKey]=useState('');const now=new Date();
 const expense=useMemo(()=>transactions.filter(t=>t.type==='expense'&&t.status!=='declined'),[transactions]);const currentYear=now.getFullYear();const viewExpense=view==='quarterly'?expense.filter(t=>Number(t.transaction_date.slice(0,4))===currentYear):expense;
 const totals=new Map<string,number>();viewExpense.forEach(t=>totals.set(t.category,(totals.get(t.category)||0)+Math.abs(Number(t.amount||0))));const categories=[...totals.entries()].sort((a,b)=>b[1]-a[1]).slice(0,3).map(([name])=>name);const years=[...new Set(expense.map(t=>Number(t.transaction_date.slice(0,4))))].filter(Boolean).sort((a,b)=>a-b);
 const groups=view==='quarterly'?[0,1,2,3].map(q=>({key:`${currentYear}-Q${q+1}`,label:`Q${q+1}`,sub:String(currentYear),partial:q===Math.floor(now.getMonth()/3),matches:(t:Tx)=>Number(t.transaction_date.slice(0,4))===currentYear&&Math.floor((Number(t.transaction_date.slice(5,7))-1)/3)===q})):years.map(year=>({key:String(year),label:String(year),sub:'Annual',partial:year===currentYear,matches:(t:Tx)=>Number(t.transaction_date.slice(0,4))===year}));
 const rows=groups.map(group=>({...group,values:categories.map(category=>expense.filter(t=>t.category===category&&group.matches(t)).reduce((s,t)=>s+Math.abs(Number(t.amount||0)),0))}));const active=rows.find(row=>row.key===selectedKey)||rows.find(row=>row.partial)||rows[rows.length-1];const max=Math.max(1,...rows.flatMap(row=>row.values));const topTotal=categories.reduce((s,c)=>s+(totals.get(c)||0),0),allTotal=[...totals.values()].reduce((s,v)=>s+v,0);
 return <section className="property-expense-trends"><div className="property-section-head"><div><h2>Expense trends</h2><p>{allTotal?Math.round(topTotal/allTotal*100):0}% of expenses are represented by the top three categories.</p></div></div><div className="expense-view-switch" aria-label="Expense trend period"><button className={view==='quarterly'?'active':''} onClick={()=>{setView('quarterly');setSelectedKey('')}}>Quarterly</button><button className={view==='annual'?'active':''} onClick={()=>{setView('annual');setSelectedKey('')}}>Annual</button></div><div className="expense-fixed-summary"><strong>{active?`${active.label}${active.partial?' · Current':''}`:'No activity'}</strong><span>{formatCurrency(active?.values.reduce((s,v)=>s+v,0)||0)} total</span></div>{categories.length?<><div className="expense-chart"><div className="expense-chart-grid" style={{gridTemplateColumns:`repeat(${Math.max(1,rows.length)},minmax(54px,1fr))`}}>{rows.map(row=><button key={row.key} onClick={()=>setSelectedKey(row.key)} className={active?.key===row.key?'active':''}><span className="expense-bars">{row.values.map((value,i)=><i key={categories[i]} style={{height:`${Math.max(value?4:0,value/max*100)}%`,background:`var(--category-${categoryKey(categories[i])})`}}/>)}</span><em>{row.label}</em><small>{row.sub}{row.partial?' · To date':''}</small></button>)}</div></div><div className="expense-chart-legend">{categories.map(category=><span key={category}><i style={{background:`var(--category-${categoryKey(category)})`}}/>{category}</span>)}</div></>:<p className="property-empty-copy">No operating expenses recorded.</p>}</section>;
}
