-- Stable visit snapshots and deterministic change events for Daily Brief.
alter table public.dashboard_visits add column if not exists previous_visit_at timestamptz;
alter table public.dashboard_visits add column if not exists current_visit_started_at timestamptz;
alter table public.dashboard_visits add column if not exists brief_items jsonb not null default '[]'::jsonb;
alter table public.dashboard_visits add column if not exists brief_opened_ids jsonb not null default '[]'::jsonb;
alter table public.dashboard_visits add column if not exists brief_resolved_ids jsonb not null default '[]'::jsonb;

create table if not exists public.app_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null, entity_type text not null, entity_id uuid, property_id uuid, unit_id uuid,
  occurred_at timestamptz not null default now(), metadata jsonb not null default '{}'::jsonb
);
alter table public.app_events enable row level security;
drop policy if exists "Users can read own app events" on public.app_events;
create policy "Users can read own app events" on public.app_events for select to authenticated using (user_id=auth.uid());

create or replace function public.capture_portfolio_event() returns trigger language plpgsql security definer set search_path=public as $$
declare r jsonb:=to_jsonb(new); o jsonb:=case when tg_op='UPDATE' then to_jsonb(old) else '{}'::jsonb end; kind text:=lower(tg_table_name); event_name text;
begin
  event_name:=case when tg_op='INSERT' then trim(trailing 's' from kind)||'_added'
    when kind='transactions' and r->>'status'='posted' and o->>'status'='pending' and r->>'category'='Rent' then 'rent_confirmed'
    when kind='transactions' and r->>'status'='declined' and o->>'status'='pending' and r->>'category'='Rent' then 'rent_declined'
    when kind='transactions' and r->>'category' is distinct from o->>'category' then 'transaction_categorized'
    when kind='units' and r->>'occupied' is distinct from o->>'occupied' then 'occupancy_changed'
    when kind='units' and r->>'lease_end_date' is distinct from o->>'lease_end_date' then 'lease_updated'
    when kind='properties' and (r->>'mortgage_balance' is distinct from o->>'mortgage_balance' or r->>'monthly_mortgage_payment' is distinct from o->>'monthly_mortgage_payment') then 'mortgage_updated'
    else trim(trailing 's' from kind)||'_updated' end;
  insert into public.app_events(user_id,event_type,entity_type,entity_id,property_id,unit_id,metadata)
  values ((r->>'user_id')::uuid,event_name,trim(trailing 's' from kind),(r->>'id')::uuid,case when kind='properties' then (r->>'id')::uuid else nullif(r->>'property_id','')::uuid end,case when kind='units' then (r->>'id')::uuid when kind='transactions' then nullif(r->>'unit_id','')::uuid else null end,jsonb_build_object('operation',tg_op));
  return new;
end $$;
do $$ declare t text; begin foreach t in array array['properties','units','transactions','documents'] loop execute format('drop trigger if exists portfolio_event_%I on public.%I',t,t);execute format('create trigger portfolio_event_%I after insert or update on public.%I for each row execute function public.capture_portfolio_event()',t,t);end loop;end $$;
