'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { usePlaidLink } from 'react-plaid-link';
import { MoreHorizontal, RefreshCw } from 'lucide-react';
import { useAuth } from '@/components/auth/AuthContext';
import { ProductSelect } from '@/components/common/ProductControls';
import { supabase } from '@/lib/supabase';
import { formatCurrency } from '@/lib/formatters';

type Item={id:string;institution_name:string;status:string;error_message:string|null;last_synced_at:string|null};
type Account={id:string;item_id:string;name:string;official_name:string|null;mask:string|null;current_balance:number|null;property_id:string|null;import_enabled:boolean};
type Property={id:string;address:string};

export default function ConnectedAccounts(){
  const {session}=useAuth();const [items,setItems]=useState<Item[]>([]);const [accounts,setAccounts]=useState<Account[]>([]);const [properties,setProperties]=useState<Property[]>([]);const [sandbox,setSandbox]=useState(false);const [linkToken,setLinkToken]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [openMenu,setOpenMenu]=useState<string|null>(null);const [error,setError]=useState('');
  const headers=useMemo(()=>({Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'}),[session.access_token]);
  const request=useCallback(async(path:string,init:RequestInit={})=>{const response=await fetch(path,{...init,headers:{...headers,...init.headers}});const json=await response.json();if(!response.ok)throw new Error(json.error||'Request failed.');return json},[headers]);
  const load=useCallback(async()=>{const [connected,propertyRows]=await Promise.all([request('/api/plaid/accounts'),supabase.from('properties').select('id,address').is('archived_at',null).order('address')]);setItems(connected.items||[]);setAccounts(connected.accounts||[]);setSandbox(Boolean(connected.sandbox));if(!propertyRows.error)setProperties((propertyRows.data||[]) as Property[]);},[request]);
  useEffect(()=>{load().catch(e=>setError(e.message))},[load]);
  const createLink=async()=>{setBusy(true);setError('');try{const data=await request('/api/plaid/link-token',{method:'POST'});setLinkToken(data.link_token);}catch(e){setError(e instanceof Error?e.message:'Could not start Plaid.')}finally{setBusy(false)}};
  const onSuccess=useCallback(async(publicToken:string,metadata:any)=>{setBusy(true);setError('');try{await request('/api/plaid/exchange',{method:'POST',body:JSON.stringify({publicToken,institution:metadata.institution})});setLinkToken(null);await load();}catch(e){setError(e instanceof Error?e.message:'Could not connect account.')}finally{setBusy(false)}},[request,load]);
  const plaid=usePlaidLink({token:linkToken,onSuccess,onExit:()=>setLinkToken(null)});useEffect(()=>{if(linkToken&&plaid.ready)plaid.open()},[linkToken,plaid.ready,plaid.open]);
  const updateAccount=async(id:string,body:object)=>{setBusy(true);setError('');try{await request(`/api/plaid/accounts/${id}`,{method:'PATCH',body:JSON.stringify(body)});await load();}catch(e){setError(e instanceof Error?e.message:'Could not update account.')}finally{setBusy(false)}};
  const sync=async(itemId:string)=>{setBusy(true);setError('');try{await request('/api/plaid/sync',{method:'POST',body:JSON.stringify({itemId})});await load();}catch(e){setError(e instanceof Error?e.message:'Could not sync accounts.')}finally{setBusy(false)}};
  const createTest=async(itemId:string)=>{setBusy(true);setError('');try{await request('/api/plaid/sandbox-transaction',{method:'POST',body:JSON.stringify({itemId})});await load();}catch(e){setError(e instanceof Error?e.message:'Could not create test transaction.')}finally{setBusy(false)}};
  const disconnect=async(item:Item)=>{if(!confirm(`Disconnect ${item.institution_name}? Existing ledger transactions will be kept and marked disconnected.`))return;setBusy(true);setOpenMenu(null);try{await request(`/api/plaid/items/${item.id}`,{method:'DELETE'});await load();}catch(e){setError(e instanceof Error?e.message:'Could not disconnect bank.')}finally{setBusy(false)}};
  return <section className="connected-accounts-setting"><div className="connected-accounts-head"><div><strong>Bank accounts</strong><span>Map each account to a property. Posted activity enters the ledger and Needs Review.</span></div><button className="product-secondary-button" onClick={createLink} disabled={busy}>{busy?'Please wait…':'Connect bank'}</button></div>{error&&<p className="connected-accounts-error">{error}</p>}{items.map(item=><section className="connected-bank" key={item.id}><header className="connected-bank-title"><div><span className="connected-bank-heading"><strong>{item.institution_name}</strong>{sandbox&&<em className="sandbox-badge">Sandbox</em>}</span><span>{item.last_synced_at?`Synced ${new Date(item.last_synced_at).toLocaleString()}`:'Ready to sync'}{item.error_message?` · ${item.error_message}`:''}</span></div><div className="connected-bank-actions"><button className="product-secondary-button" onClick={()=>sync(item.id)} disabled={busy}><RefreshCw size={16}/>Sync</button>{sandbox&&<button className="product-secondary-button" onClick={()=>createTest(item.id)} disabled={busy}>Create test transaction</button>}<div className="connected-bank-menu"><button onClick={()=>setOpenMenu(openMenu===item.id?null:item.id)} aria-label={`Options for ${item.institution_name}`}><MoreHorizontal size={18}/></button>{openMenu===item.id&&<button className="connected-disconnect" onClick={()=>disconnect(item)}>Disconnect bank</button>}</div></div></header><div className="connected-bank-accounts">{accounts.filter(account=>account.item_id===item.id).map(account=><div className="connected-bank-account" key={account.id}><div className="connected-account-copy"><strong>{account.official_name||account.name}{account.mask?` •••• ${account.mask}`:''}</strong><span>{formatCurrency(account.current_balance||0)} current balance · {account.import_enabled?'Importing activity':'Import paused'}</span></div><div className="connected-account-controls"><ProductSelect aria-label={`Property for ${account.name}`} value={account.property_id||''} disabled={busy} onChange={event=>updateAccount(account.id,{propertyId:event.target.value})}><option value="">Choose property</option>{properties.map(property=><option value={property.id} key={property.id}>{property.address}</option>)}</ProductSelect><button className="connected-import-toggle" disabled={busy} onClick={()=>updateAccount(account.id,{importEnabled:!account.import_enabled})}>{account.import_enabled?'Stop importing':'Resume importing'}</button></div></div>)}</div></section>)}{!items.length&&!error&&<p className="connected-accounts-empty">No banks connected yet. Sandbox connects only to test-bank data.</p>}</section>;
}
