'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { usePlaidLink } from 'react-plaid-link';
import { Landmark, MoreHorizontal, RefreshCw } from 'lucide-react';
import { useAuth } from '@/components/auth/AuthContext';
import { ProductSelect } from '@/components/common/ProductControls';
import { Button } from '@/components/ui/Button';
import { supabase } from '@/lib/supabase';
import { formatCurrency } from '@/lib/formatters';

type Item={id:string;institution_name:string;status:string;error_message:string|null;last_synced_at:string|null};
type Account={id:string;item_id:string;name:string;official_name:string|null;mask:string|null;type:string;subtype:string|null;current_balance:number|null;property_id:string|null;import_enabled:boolean};
type Property={id:string;address:string};

export default function ConnectedAccounts(){
  const {session}=useAuth();const [items,setItems]=useState<Item[]>([]);const [accounts,setAccounts]=useState<Account[]>([]);const [properties,setProperties]=useState<Property[]>([]);const [sandbox,setSandbox]=useState(false);const [testProperty,setTestProperty]=useState('');const [linkToken,setLinkToken]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [openMenu,setOpenMenu]=useState<string|null>(null);const [error,setError]=useState('');const [notice,setNotice]=useState('');
  const headers=useMemo(()=>({Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'}),[session.access_token]);
  const request=useCallback(async(path:string,init:RequestInit={},retry=true):Promise<any>=>{const response=await fetch(path,{...init,headers:{...headers,...init.headers}});if(response.status===401&&retry){const refreshed=await supabase.auth.refreshSession();const token=refreshed.data.session?.access_token;if(token)return request(path,{...init,headers:{...init.headers,Authorization:`Bearer ${token}`}},false)}const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error||'Request failed.');return json},[headers]);
  const load=useCallback(async()=>{const [connected,propertyRows]=await Promise.all([request('/api/plaid/accounts'),supabase.from('properties').select('id,address').is('archived_at',null).order('address')]);setItems(connected.items||[]);setAccounts(connected.accounts||[]);setSandbox(Boolean(connected.sandbox));if(!propertyRows.error){const rows=(propertyRows.data||[]) as Property[];setProperties(rows);setTestProperty(value=>value||rows[0]?.id||'')}},[request]);
  useEffect(()=>{load().catch(e=>setError(e.message))},[load]);
  useEffect(()=>{if(!notice)return;const timer=window.setTimeout(()=>setNotice(''),4000);return()=>window.clearTimeout(timer)},[notice]);
  const createLink=async()=>{setBusy(true);setError('');setNotice('');try{const data=await request('/api/plaid/link-token',{method:'POST'});setLinkToken(data.link_token)}catch(e){setError(e instanceof Error?e.message:'Could not start Plaid.')}finally{setBusy(false)}};
  const onSuccess=useCallback(async(publicToken:string,metadata:any)=>{setBusy(true);setError('');try{const selectedAccountIds=(metadata.accounts||[]).map((account:any)=>account.id||account.account_id).filter(Boolean);const result=await request('/api/plaid/exchange',{method:'POST',body:JSON.stringify({publicToken,institution:metadata.institution,selectedAccountIds})});setLinkToken(null);setNotice(`${result.accountCount||0} account${result.accountCount===1?'':'s'} linked. Choose a property to begin importing.`);await load()}catch(e){setError(e instanceof Error?e.message:'Could not link bank.')}finally{setBusy(false)}},[request,load]);
  const plaid=usePlaidLink({token:linkToken,onSuccess,onExit:()=>setLinkToken(null)});useEffect(()=>{if(linkToken&&plaid.ready)plaid.open()},[linkToken,plaid.ready,plaid.open]);
  const updateAccount=async(id:string,propertyId:string)=>{setBusy(true);setError('');setNotice('');try{await request(`/api/plaid/accounts/${id}`,{method:'PATCH',body:JSON.stringify({propertyId})});setNotice(propertyId?'Account linked. Future activity will import to this property.':'Account is inactive and will not affect the ledger.');await load()}catch(e){setError(e instanceof Error?e.message:'Could not update account.')}finally{setBusy(false)}};
  const sync=async(itemId:string)=>{setBusy(true);setError('');setNotice('');try{const result=await request('/api/plaid/sync',{method:'POST',body:JSON.stringify({itemId})});const added=(result.results||[]).reduce((sum:number,row:any)=>sum+(row.added||0),0);setNotice(added?`${added} new bank transaction${added===1?'':'s'} imported.`:'Accounts are up to date.');await load()}catch(e){setError(e instanceof Error?e.message:'Could not sync accounts.')}finally{setBusy(false)}};
  const createTest=async()=>{if(!testProperty){setError('Choose a property for the Sandbox test.');return}setBusy(true);setError('');setNotice('');try{const result=await request('/api/plaid/sandbox-transaction',{method:'POST',body:JSON.stringify({propertyId:testProperty})});setNotice(result.message||'Sandbox test is ready.');await load()}catch(e){setError(e instanceof Error?e.message:'Could not create the Sandbox test.')}finally{setBusy(false)}};
  const resetSandbox=async()=>{if(!confirm('Reset Sandbox Test Bank? This removes only its test accounts and imported sample transactions.'))return;setBusy(true);setError('');try{await request('/api/plaid/sandbox-reset',{method:'POST'});setNotice('Sandbox test data reset.');await load()}catch(e){setError(e instanceof Error?e.message:'Could not reset Sandbox data.')}finally{setBusy(false)}};
  const unlinkAccount=async(account:Account)=>{if(!confirm(`Unlink ${account.official_name||account.name}? Imported history will be kept.`))return;setBusy(true);setOpenMenu(null);setError('');try{await request(`/api/plaid/accounts/${account.id}`,{method:'DELETE'});setNotice('Account unlinked. Imported history was kept.');await load()}catch(e){setError(e instanceof Error?e.message:'Could not unlink account.')}finally{setBusy(false)}};
  const unlinkBank=async(item:Item)=>{if(!confirm(`Unlink ${item.institution_name}? All accounts under this bank will stop importing. Imported history will be kept.`))return;setBusy(true);setOpenMenu(null);setError('');try{await request(`/api/plaid/items/${item.id}`,{method:'DELETE'});setNotice('Bank unlinked. Imported history was kept.');await load()}catch(e){setError(e instanceof Error?e.message:'Could not unlink bank.')}finally{setBusy(false)}};

  return <section className="connected-accounts-setting">
    <div className="connected-accounts-head"><div><strong>Bank accounts</strong><span>Assign each account to a property before activity enters your ledger.</span></div><Button variant="secondary" onClick={createLink} disabled={busy}>{busy?'Please wait…':'Link bank'}</Button></div>
    {error&&<p className="connected-accounts-error" role="alert">{error}</p>}{notice&&<p className="connected-accounts-notice" role="status">{notice}</p>}
    <div className="connected-bank-list">{items.map(item=>{const bankAccounts=accounts.filter(account=>account.item_id===item.id);return <section className="connected-bank" key={item.id}>
      <header className="connected-bank-title"><div className="connected-bank-identity"><Landmark size={20}/><div><span className="connected-bank-heading"><strong>{item.institution_name}</strong>{item.institution_name==='Sandbox Test Bank'&&<em className="sandbox-badge">Sandbox</em>}</span><span>{item.last_synced_at?`Synced ${new Date(item.last_synced_at).toLocaleString()}`:'Linked'}{item.error_message?` · ${item.error_message}`:''}</span></div></div><div className="connected-bank-actions"><button className="connected-sync" onClick={()=>sync(item.id)} disabled={busy}><RefreshCw size={16}/>Sync</button><div className="connected-bank-menu"><button onClick={()=>setOpenMenu(openMenu===`bank:${item.id}`?null:`bank:${item.id}`)} aria-label={`Options for ${item.institution_name}`}><MoreHorizontal size={18}/></button>{openMenu===`bank:${item.id}`&&<button className="connected-unlink-menu" onClick={()=>unlinkBank(item)}>Unlink bank</button>}</div></div></header>
      <div className="connected-bank-accounts">{bankAccounts.map(account=><div className="connected-bank-account" key={account.id}><div className="connected-account-copy"><strong>{account.official_name||account.name}{account.mask?` •••• ${account.mask}`:''}</strong><span>{account.subtype||account.type} · {formatCurrency(account.current_balance||0)}</span><em className={account.import_enabled&&account.property_id?'active':'inactive'}>{account.import_enabled&&account.property_id?'Linked':'Needs property'}</em></div><div className="connected-account-controls"><ProductSelect label="Assigned property" aria-label={`Property for ${account.name}`} value={account.property_id||''} disabled={busy} onChange={event=>updateAccount(account.id,event.target.value)}><option value="">Choose property</option>{properties.map(property=><option value={property.id} key={property.id}>{property.address}</option>)}</ProductSelect><div className="connected-bank-menu"><button onClick={()=>setOpenMenu(openMenu===`account:${account.id}`?null:`account:${account.id}`)} aria-label={`Options for ${account.name}`}><MoreHorizontal size={18}/></button>{openMenu===`account:${account.id}`&&<button className="connected-unlink-menu" onClick={()=>unlinkAccount(account)}>Unlink account</button>}</div></div></div>)}</div>
    </section>})}</div>
    {!items.length&&!error&&<p className="connected-accounts-empty">No banks linked yet.</p>}
    {sandbox&&<section className="connected-sandbox-tools"><div><strong>Testing tools</strong><span>Create a Sandbox Test Bank account and one $64 imported expense.</span></div><ProductSelect label="Assigned property" aria-label="Property for Sandbox test" value={testProperty} onChange={event=>setTestProperty(event.target.value)}><option value="">Choose property</option>{properties.map(property=><option value={property.id} key={property.id}>{property.address}</option>)}</ProductSelect><Button variant="secondary" onClick={createTest} disabled={busy||!testProperty}>Create test transaction</Button><Button variant="destructive" onClick={resetSandbox} disabled={busy}>Reset Sandbox data</Button></section>}
  </section>
}
