'use client';

import React, { useState } from 'react';
import { supabase } from '@/lib/supabase';
import type { Property } from '@/lib/types';

export default function PropertyEditModal({property,onClose,onSaved}:{property:Property;onClose:()=>void;onSaved:(patch:Record<string,unknown>)=>void}){
  const p=property as any;
  const [form,setForm]=useState({address:p.address||'',city:p.city||'',state:p.state||'',zip:p.zip||'',property_type:p.property_type||'duplex',purchase_price:String(p.purchase_price||''),purchase_date:p.purchase_date||'',mortgage_balance:String(p.mortgage_balance||''),monthly_mortgage_payment:String(p.monthly_mortgage_payment||''),mortgage_start_date:p.mortgage_start_date||'',mortgage_recurring_enabled:p.mortgage_recurring_enabled!==false});
  const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');const patch={address:form.address.trim(),city:form.city.trim(),state:form.state.trim(),zip:form.zip.trim(),property_type:form.property_type,purchase_price:form.purchase_price?Number(form.purchase_price):null,purchase_date:form.purchase_date||null,mortgage_balance:Number(form.mortgage_balance||0),monthly_mortgage_payment:Number(form.monthly_mortgage_payment||0),mortgage_start_date:form.mortgage_start_date||null,mortgage_recurring_enabled:form.mortgage_recurring_enabled};const r=await supabase.from('properties').update(patch).eq('id',property.id);setSaving(false);if(r.error){setError(r.error.message);return;}onSaved(patch);};
  const deleteMortgage=async()=>{if(!confirm('Delete the mortgage setup? Posted ledger transactions will be preserved.'))return;setSaving(true);setError('');const patch={mortgage_balance:0,monthly_mortgage_payment:0,mortgage_start_date:null,mortgage_recurring_enabled:false};const r=await supabase.from('properties').update(patch).eq('id',property.id);setSaving(false);if(r.error){setError(r.error.message);return;}setForm(current=>({...current,mortgage_balance:'',monthly_mortgage_payment:'',mortgage_start_date:'',mortgage_recurring_enabled:false}));onSaved(patch);};
  return <div className="workspace-modal-overlay"><div className="workspace-modal property-edit-modal"><div className="workspace-modal-head"><div><div className="eyebrow">PROPERTY</div><h2>Edit property</h2></div><button type="button" className="workspace-modal-close" onClick={onClose}>×</button></div>{error&&<div className="workspace-form-error">{error}</div>}<form onSubmit={save} className="workspace-form"><div className="workspace-form-grid two"><label>Address<input required value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>Property type<select value={form.property_type} onChange={e=>setForm({...form,property_type:e.target.value})}><option value="duplex">Duplex</option><option value="single_family">Single family</option><option value="triplex">Triplex</option><option value="multi_unit">Multi-unit</option></select></label></div><div className="workspace-form-grid three"><label>City<input required value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>State<input required value={form.state} onChange={e=>setForm({...form,state:e.target.value})}/></label><label>ZIP<input required value={form.zip} onChange={e=>setForm({...form,zip:e.target.value})}/></label></div><div className="workspace-form-grid two"><label>Purchase price<input type="number" min="0" step="0.01" value={form.purchase_price} onChange={e=>setForm({...form,purchase_price:e.target.value})}/></label><label>Purchase date<input type="date" value={form.purchase_date} onChange={e=>setForm({...form,purchase_date:e.target.value})}/></label></div><div className="workspace-form-divider"/><div className="workspace-form-grid two"><label>Mortgage balance<input type="number" min="0" step="1" value={form.mortgage_balance} onChange={e=>setForm({...form,mortgage_balance:e.target.value})}/></label><label>Monthly mortgage payment<input type="number" min="0" step="1" value={form.monthly_mortgage_payment} onChange={e=>setForm({...form,monthly_mortgage_payment:e.target.value})}/></label></div><div className="workspace-form-grid two"><label>Mortgage start date<input type="date" value={form.mortgage_start_date} onChange={e=>setForm({...form,mortgage_start_date:e.target.value})}/></label><label className="workspace-checkbox"><input type="checkbox" checked={form.mortgage_recurring_enabled} onChange={e=>setForm({...form,mortgage_recurring_enabled:e.target.checked})}/>Post monthly mortgage automatically</label></div>{(Number(form.mortgage_balance)>0||Number(form.monthly_mortgage_payment)>0)&&<button type="button" className="transaction-archive-button mortgage-delete-button" disabled={saving} onClick={deleteMortgage}>Delete mortgage setup</button>}<div className="workspace-modal-footer"><button type="button" className="property-secondary-action" onClick={onClose}>Cancel</button><button disabled={saving} className="workspace-primary-button">{saving?'Saving…':'Save property'}</button></div></form></div></div>;
}
