'use client';

import React, { useState } from 'react';
import { supabase } from '@/lib/supabase';
import type { Property } from '@/lib/types';
import { SecondaryButton } from '@/components/common/ProductControls';

export default function PropertyEditModal({property,onClose,onSaved}:{property:Property;onClose:()=>void;onSaved:(patch:Record<string,unknown>)=>void}){
  const p=property;
  const inferredPI=Math.max(0,Number(p.monthly_mortgage_payment||0)-Number(p.mortgage_escrow_amount||0)-Number(p.mortgage_pmi_amount||0));
  const [form,setForm]=useState({address:p.address||'',city:p.city||'',state:p.state||'',zip:p.zip||'',property_type:p.property_type||'duplex',purchase_price:String(p.purchase_price||''),purchase_date:p.purchase_date||'',mortgage_balance:String(p.mortgage_balance||''),mortgage_interest_rate:String(p.mortgage_interest_rate||''),mortgage_term_years:String(p.mortgage_term_years||30),mortgage_principal_interest_payment:String(p.mortgage_principal_interest_payment||inferredPI||''),mortgage_escrow_amount:String(p.mortgage_escrow_amount||''),mortgage_pmi_amount:String(p.mortgage_pmi_amount||''),mortgage_start_date:p.mortgage_start_date||'',mortgage_recurring_enabled:p.mortgage_recurring_enabled!==false});
  const [saving,setSaving]=useState(false),[error,setError]=useState('');
  const totalPayment=Number(form.mortgage_principal_interest_payment||0)+Number(form.mortgage_escrow_amount||0)+Number(form.mortgage_pmi_amount||0);
  const mortgagePatch=()=>({mortgage_balance:Number(form.mortgage_balance||0),monthly_mortgage_payment:totalPayment,mortgage_interest_rate:form.mortgage_interest_rate?Number(form.mortgage_interest_rate):null,mortgage_term_years:form.mortgage_term_years?Number(form.mortgage_term_years):null,mortgage_principal_interest_payment:form.mortgage_principal_interest_payment?Number(form.mortgage_principal_interest_payment):null,mortgage_escrow_amount:form.mortgage_escrow_amount?Number(form.mortgage_escrow_amount):null,mortgage_pmi_amount:form.mortgage_pmi_amount?Number(form.mortgage_pmi_amount):null,mortgage_start_date:form.mortgage_start_date||null,mortgage_recurring_enabled:form.mortgage_recurring_enabled});
  const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');const patch={address:form.address.trim(),city:form.city.trim(),state:form.state.trim(),zip:form.zip.trim(),property_type:form.property_type,purchase_price:form.purchase_price?Number(form.purchase_price):null,purchase_date:form.purchase_date||null,...mortgagePatch()};const r=await supabase.from('properties').update(patch).eq('id',property.id);setSaving(false);if(r.error){setError(r.error.message);return}onSaved(patch)};
  const deleteMortgage=async()=>{if(!confirm('Delete the mortgage setup? Posted ledger transactions will be preserved.'))return;setSaving(true);setError('');const patch={mortgage_balance:0,monthly_mortgage_payment:0,mortgage_interest_rate:null,mortgage_term_years:null,mortgage_principal_interest_payment:null,mortgage_escrow_amount:null,mortgage_pmi_amount:null,mortgage_start_date:null,mortgage_recurring_enabled:false};const r=await supabase.from('properties').update(patch).eq('id',property.id);setSaving(false);if(r.error){setError(r.error.message);return}onSaved(patch)};
  return <div className="workspace-modal-overlay"><div className="workspace-modal property-edit-modal"><div className="workspace-modal-head"><div><div className="eyebrow">PROPERTY</div><h2>Edit property</h2></div><button type="button" className="workspace-modal-close" onClick={onClose}>×</button></div>{error&&<div className="workspace-form-error">{error}</div>}<form onSubmit={save} className="workspace-form">
    <div className="workspace-form-grid two"><label>Address<input required value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>Property type<select value={form.property_type} onChange={e=>setForm({...form,property_type:e.target.value})}><option value="duplex">Duplex</option><option value="single_family">Single family</option><option value="triplex">Triplex</option><option value="multi_unit">Multi-unit</option></select></label></div>
    <div className="workspace-form-grid three"><label>City<input required value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>State<input required value={form.state} onChange={e=>setForm({...form,state:e.target.value})}/></label><label>ZIP<input required value={form.zip} onChange={e=>setForm({...form,zip:e.target.value})}/></label></div>
    <div className="workspace-form-grid two"><label>Purchase price<input type="number" min="0" step="0.01" value={form.purchase_price} onChange={e=>setForm({...form,purchase_price:e.target.value})}/></label><label>Purchase date<input type="date" value={form.purchase_date} onChange={e=>setForm({...form,purchase_date:e.target.value})}/></label></div>
    <div className="workspace-form-divider"/><h3 className="workspace-form-section-title">Mortgage</h3>
    <div className="workspace-form-grid two"><label>Current balance<input type="number" min="0" step="1" value={form.mortgage_balance} onChange={e=>setForm({...form,mortgage_balance:e.target.value})}/></label><label>Interest rate<input type="number" min="0" step="0.001" placeholder="6.75" value={form.mortgage_interest_rate} onChange={e=>setForm({...form,mortgage_interest_rate:e.target.value})}/></label></div>
    <div className="workspace-form-grid two"><label>Original term<select value={form.mortgage_term_years} onChange={e=>setForm({...form,mortgage_term_years:e.target.value})}><option value="15">15 years</option><option value="20">20 years</option><option value="30">30 years</option></select></label><label>Mortgage start date<input type="date" value={form.mortgage_start_date} onChange={e=>setForm({...form,mortgage_start_date:e.target.value})}/></label></div>
    <div className="workspace-form-grid mortgage-payment-grid"><label>Monthly P&amp;I<input type="number" min="0" step="0.01" value={form.mortgage_principal_interest_payment} onChange={e=>setForm({...form,mortgage_principal_interest_payment:e.target.value})}/></label><label>Monthly escrow <small>Optional</small><input type="number" min="0" step="0.01" value={form.mortgage_escrow_amount} onChange={e=>setForm({...form,mortgage_escrow_amount:e.target.value})}/></label><label>PMI <small>Optional</small><input type="number" min="0" step="0.01" value={form.mortgage_pmi_amount} onChange={e=>setForm({...form,mortgage_pmi_amount:e.target.value})}/></label><label>Total payment<input type="number" value={totalPayment||''} readOnly aria-readonly="true"/></label></div>
    <label className="workspace-checkbox"><input type="checkbox" checked={form.mortgage_recurring_enabled} onChange={e=>setForm({...form,mortgage_recurring_enabled:e.target.checked})}/>Post monthly mortgage automatically</label>
    {(Number(form.mortgage_balance)>0||totalPayment>0)&&<button type="button" className="transaction-archive-button mortgage-delete-button" disabled={saving} onClick={deleteMortgage}>Delete mortgage setup</button>}
    <div className="workspace-modal-footer"><SecondaryButton onClick={onClose}>Cancel</SecondaryButton><button disabled={saving} className="workspace-primary-button">{saving?'Saving…':'Save property'}</button></div>
  </form></div></div>;
}
