import { Products } from 'plaid';
import { apiError, adminDb, authenticatedUser, encryptToken, plaidClient } from '@/lib/plaid/server';
import { syncPlaidItem } from '@/lib/plaid/sync';

export const runtime='nodejs';

export async function POST(request:Request){try{
  const user=await authenticatedUser(request);
  if((process.env.PLAID_ENV||'sandbox').toLowerCase()!=='sandbox')return Response.json({error:'Sandbox testing is not available in this environment.'},{status:403});
  const {propertyId}=await request.json();if(!propertyId)return Response.json({error:'Choose a property for the test account.'},{status:400});
  const db=adminDb();const {data:property,error:propertyError}=await db.from('properties').select('id,address').eq('id',propertyId).eq('user_id',user.id).is('archived_at',null).single();if(propertyError||!property)return Response.json({error:'The selected property was not found.'},{status:404});
  let {data:item}=await db.from('plaid_items').select('*').eq('user_id',user.id).eq('institution_id','re_portal_sandbox_fixture').is('disconnected_at',null).maybeSingle();
  if(!item){const plaid=plaidClient();const token=await plaid.sandboxPublicTokenCreate({institution_id:'ins_109508',initial_products:[Products.Transactions],options:{override_username:'user_good',override_password:'pass_good'}} as any);const exchange=await plaid.itemPublicTokenExchange({public_token:token.data.public_token});const accounts=await plaid.accountsGet({access_token:exchange.data.access_token});const checking=accounts.data.accounts.find(account=>account.type==='depository'&&account.subtype==='checking');if(!checking)throw new Error('Plaid did not return a Sandbox checking account.');const savedItem=await db.from('plaid_items').insert({user_id:user.id,plaid_item_id:exchange.data.item_id,access_token_encrypted:encryptToken(exchange.data.access_token),institution_id:'re_portal_sandbox_fixture',institution_name:'Sandbox Test Bank',status:'connected'}).select().single();if(savedItem.error)throw savedItem.error;item=savedItem.data;const savedAccount=await db.from('plaid_accounts').insert({user_id:user.id,item_id:item.id,plaid_account_id:checking.account_id,name:'Test Checking',official_name:'RE Portal Sandbox Checking',mask:'4242',type:'depository',subtype:'checking',current_balance:checking.balances.current,available_balance:checking.balances.available,iso_currency_code:'USD',property_id:propertyId,import_enabled:true,stopped_at:null}).select().single();if(savedAccount.error)throw savedAccount.error;
  }else{await db.from('plaid_accounts').update({property_id:propertyId,import_enabled:true,stopped_at:null,archived_at:null}).eq('item_id',item.id);await syncPlaidItem(db,item);}
  const {data:account,error:accountError}=await db.from('plaid_accounts').select('id,mask').eq('item_id',item.id).is('archived_at',null).limit(1).single();if(accountError)throw accountError;
  const importKey=`plaid:sandbox-fixture:${item.id}`;const {data:existing}=await db.from('transactions').select('id').eq('user_id',user.id).eq('import_key',importKey).maybeSingle();if(!existing){const inserted=await db.from('transactions').insert({user_id:user.id,property_id:propertyId,unit_id:null,transaction_date:new Date().toISOString().slice(0,10),type:'expense',category:'Needs Review',description:'Sandbox test repair',payee_source:'RE Portal Test Merchant',amount:-64,notes:'Controlled Plaid Sandbox test expense',source:'plaid',source_institution:'Sandbox Test Bank',source_account_mask:account.mask||'4242',source_connection_status:'connected',import_key:importKey,status:'posted',confirmed_at:new Date().toISOString(),needs_review:true,is_new_import:true,import_acknowledged_at:null});if(inserted.error)throw inserted.error;}
  return Response.json({ok:true,created:!existing,message:`Test expense added to ${property.address}. Open New imports in Ledger.`});
}catch(error){return apiError(error)}}
