import type { Property, Unit, Transaction } from './types';

export const mockProperty: Property = {
  id: 'prop-1',
  address: '15334 Triskett Rd',
  city: 'Cleveland',
  state: 'OH',
  zip: '44111',
  mortgage_balance: 142000,
  property_type: 'multi_unit',
};

export const mockUnits: Unit[] = [
  {
    id: 'unit-1',
    property_id: 'prop-1',
    unit_number: 'Unit #1',
    bedroom_count: 3,
    bathroom_count: 1.5,
    sqft: 1500,
    current_rent: 1425,
    tenant_name: 'Kenyetta Frazier',
    occupied: true,
  },
  {
    id: 'unit-2',
    property_id: 'prop-1',
    unit_number: 'Unit #2',
    bedroom_count: 3,
    bathroom_count: 1.5,
    sqft: 1500,
    current_rent: 1425,
    tenant_name: 'Janet M Perez',
    occupied: true,
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: 'tx-1',
    property_id: 'prop-1',
    transaction_date: '2026-08-20',
    type: 'income',
    category: 'Rent',
    description: 'Rent - Unit #1',
    payee_source: 'Kenyetta Frazier',
    amount: 1425,
    notes: null,
  },
  {
    id: 'tx-2',
    property_id: 'prop-1',
    transaction_date: '2026-08-04',
    type: 'income',
    category: 'Rent',
    description: 'Rent - Unit #2',
    payee_source: 'Janet M Perez',
    amount: 1425,
    notes: null,
  },
  {
    id: 'tx-3',
    property_id: 'prop-1',
    transaction_date: '2026-08-03',
    type: 'income',
    category: 'Rent',
    description: 'Rent - Unit #1',
    payee_source: 'Kenyetta Frazier',
    amount: 1425,
    notes: null,
  },
  {
    id: 'tx-4',
    property_id: 'prop-1',
    transaction_date: '2026-08-20',
    type: 'expense',
    category: 'Other',
    description: 'Rental Concession Refund',
    payee_source: null,
    amount: -5,
    notes: null,
  },
  {
    id: 'tx-5',
    property_id: 'prop-1',
    transaction_date: '2026-08-13',
    type: 'expense',
    category: 'Other',
    description: 'In-House Maintenance',
    payee_source: 'DVC Maintenance',
    amount: -512.5,
    notes: null,
  },
  {
    id: 'tx-6',
    property_id: 'prop-1',
    transaction_date: '2026-08-13',
    type: 'expense',
    category: 'Other',
    description: 'Materials',
    payee_source: 'DVC Maintenance',
    amount: -32,
    notes: null,
  },
  {
    id: 'tx-7',
    property_id: 'prop-1',
    transaction_date: '2026-08-13',
    type: 'expense',
    category: 'Management Fee',
    description: 'Management Fee for 08/2026',
    payee_source: 'Doorvest',
    amount: -114,
    notes: null,
  },
  {
    id: 'tx-8',
    property_id: 'prop-1',
    transaction_date: '2026-08-10',
    type: 'transfer',
    category: 'Other',
    description: 'Owner Distribution',
    payee_source: 'Andres Maldonado',
    amount: 2322,
    notes: null,
  },
  {
    id: 'tx-9',
    property_id: 'prop-1',
    transaction_date: '2026-07-21',
    type: 'transfer',
    category: 'Other',
    description: 'Owner Balance Forward',
    payee_source: 'Andres Maldonado',
    amount: 300,
    notes: null,
  },
  {
    id: 'tx-10',
    property_id: 'prop-1',
    transaction_date: '2026-07-20',
    type: 'expense',
    category: 'Management Fee',
    description: 'Management Fee for 07/2026',
    payee_source: 'Doorvest',
    amount: -114,
    notes: null,
  },
  {
    id: 'tx-11',
    property_id: 'prop-1',
    transaction_date: '2026-07-15',
    type: 'income',
    category: 'Rent',
    description: 'Resident Portal Payment - Unit #2',
    payee_source: 'Janet M Perez',
    amount: 1425,
    notes: null,
  },
  {
    id: 'tx-12',
    property_id: 'prop-1',
    transaction_date: '2026-07-04',
    type: 'income',
    category: 'Rent',
    description: 'Rent - Unit #2',
    payee_source: 'Janet M Perez',
    amount: 1425,
    notes: null,
  },
];
