'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { supabase } from '@/lib/supabase';
import type { Property, UtilityAccount } from '@/lib/types';

const types=['Electric','Gas','Water','Sewer','Internet','Trash','Other'];
const empty={property_id:'',utility_type:'Electric',provider:'',account_number:'',username_email:'',login_url:'',autopay:false,responsibility:'Owner' as const,billing_cycle:'',password_reference:'',notes:''};

export default function UtilitiesPage(){
  const [items,setItems]=useState<UtilityAccount[]>([]); const [properties,setProperties]=useState<Property[]>([]); const [selected,setSelected]=useState('');
  const [show,setShow]=useState(false); const [editing,setEditing]=useState<UtilityAccount|null>(null); const [form,setForm]=useState<any>(empty); const [error,setError]=useState(''); const [loading,setLoading]=useState(true);
  async function load(){setLoading(true);const [u,p]=await Promise.all([supabase.from('utility_accounts').select('*').order('utility_type'),supabase.from('properties').select('*').order('address')]);if(u.error||p.error)setError((u.error||p.error)?.message||'Could not load utilities');else{setItems((u.data||[]) as UtilityAccount[]);setProperties((p.data||[]) as Property[]);}setLoading(false)}
  useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>items.filter(x=>!selected||x.property_id===selected),[items,selected]);
  const propertyName=(id:string)=>properties.find(p=>p.id===id)?.address||'Unknown property';
  function add(){setEditing(null);setForm({...empty,property_id:selected||properties[0]?.id||''});setShow(true)}
  function edit(x:UtilityAccount){setEditing(x);setForm({property_id:x.property_id,utility_type:x.utility_type,provider:x.provider,account_number:x.account_number||'',username_email:x.username_email||'',login_url:x.login_url||'',autopay:x.autopay,responsibility:x.responsibility,billing_cycle:x.billing_cycle||'',password_reference:x.password_reference||'',notes:x.notes||''});setShow(true)}
  async function save(e:FormEvent){e.preventDefault();setError('');const {data:a}=await supabase.auth.getUser();if(!a.user){setError('You are not signed in.');return}const payload={...form,user_id:a.user.id,account_number:form.account_number||null,username_email:form.username_email||null,login_url:form.login_url||null,billing_cycle:form.billing_cycle||null,password_reference:form.password_reference||null,notes:form.notes||null};const r=editing?await supabase.from('utility_accounts').update(payload).eq('id',editing.id):await supabase.from('utility_accounts').insert(payload);if(r.error)setError(r.error.message);else{setShow(false);await load()}}
  async function del(x:UtilityAccount){if(!confirm(`Delete ${x.provider}?`))return;const r=await supabase.from('utility_accounts').delete().eq('id',x.id);if(r.error)setError(r.error.message);else await load()}
  return <div style={{padding:24,maxWidth:1200,margin:'0 auto'}}>
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'end',gap:16,flexWrap:'wrap',marginBottom:22}}><div><h1 style={{fontSize:30,fontWeight:600}}>Utilities</h1><p style={{fontSize:14,color:'var(--text-secondary)',marginTop:5}}>Keep service accounts and login details organized by property.</p></div><button onClick={add} disabled={!properties.length} style={primary}>+ Add utility</button></div>
    {error&&<div style={errorBox}>{error}</div>}
    <label style={{display:'grid',gap:6,fontSize:13,maxWidth:360,marginBottom:20}}>Select property<select value={selected} onChange={e=>setSelected(e.target.value)} style={input}><option value="">All properties</option>{properties.map(p=><option key={p.id} value={p.id}>{p.address}</option>)}</select></label>
    <div style={{padding:'12px 14px',border:'1px solid var(--border-color)',borderRadius:10,color:'var(--text-secondary)',fontSize:13,marginBottom:18}}>Passwords are intentionally not stored here. Use “Password reference” for something like “1Password → Cleveland Water”.</div>
    {loading?<p>Loading…</p>:filtered.length===0?<div className="card" style={{padding:28,color:'var(--text-secondary)'}}>No utility accounts yet.</div>:<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:12}}>{filtered.map(x=><div key={x.id} className="card" style={{padding:18}}><div style={{fontSize:12,color:'var(--text-secondary)'}}>{x.utility_type} · {propertyName(x.property_id)}</div><div style={{fontSize:18,fontWeight:650,marginTop:4}}>{x.provider}</div><div style={{display:'grid',gap:7,marginTop:15,fontSize:13}}>{x.account_number&&<Row l="Account" v={x.account_number}/>} {x.username_email&&<Row l="Username" v={x.username_email}/>}<Row l="Autopay" v={x.autopay?'On':'Off'}/><Row l="Responsibility" v={x.responsibility}/>{x.password_reference&&<Row l="Password" v={x.password_reference}/>}</div><div style={{display:'flex',gap:8,marginTop:16}}>{x.login_url&&<button onClick={()=>window.open(x.login_url!,'_blank','noopener,noreferrer')} style={secondary}>Open provider</button>}<button onClick={()=>edit(x)} style={secondary}>Edit</button><button onClick={()=>del(x)} style={danger}>Delete</button></div></div>)}</div>}
    {show&&<Modal title={editing?'Edit utility':'Add utility'} onClose={()=>setShow(false)}><form onSubmit={save} style={{display:'grid',gap:12}}><Field label="Property"><select required value={form.property_id} onChange={e=>setForm({...form,property_id:e.target.value})} style={input}>{properties.map(p=><option key={p.id} value={p.id}>{p.address}</option>)}</select></Field><div style={two}><Field label="Utility type"><select value={form.utility_type} onChange={e=>setForm({...form,utility_type:e.target.value})} style={input}>{types.map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Provider"><input required value={form.provider} onChange={e=>setForm({...form,provider:e.target.value})} style={input}/></Field></div><div style={two}><Field label="Account number"><input value={form.account_number} onChange={e=>setForm({...form,account_number:e.target.value})} style={input}/></Field><Field label="Username / email"><input value={form.username_email} onChange={e=>setForm({...form,username_email:e.target.value})} style={input}/></Field></div><Field label="Provider login URL"><input placeholder="https://..." value={form.login_url} onChange={e=>setForm({...form,login_url:e.target.value})} style={input}/></Field><div style={two}><Field label="Responsibility"><select value={form.responsibility} onChange={e=>setForm({...form,responsibility:e.target.value})} style={input}><option>Owner</option><option>Tenant</option><option>Shared</option></select></Field><Field label="Billing cycle"><input placeholder="Monthly" value={form.billing_cycle} onChange={e=>setForm({...form,billing_cycle:e.target.value})} style={input}/></Field></div><label style={{display:'flex',gap:9,alignItems:'center',fontSize:13}}><input type="checkbox" checked={form.autopay} onChange={e=>setForm({...form,autopay:e.target.checked})}/>Autopay enabled</label><Field label="Password reference"><input placeholder="e.g. 1Password → Cleveland Water" value={form.password_reference} onChange={e=>setForm({...form,password_reference:e.target.value})} style={input}/></Field><Field label="Notes"><textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} style={input}/></Field><button style={primary}>Save utility</button></form></Modal>}
  </div>
}
function Row({l,v}:{l:string;v:string}){return <div style={{display:'grid',gridTemplateColumns:'90px 1fr',gap:10}}><span style={{color:'var(--text-secondary)'}}>{l}</span><span>{v}</span></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{display:'grid',gap:6,fontSize:13}}>{label}{children}</label>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div style={{position:'fixed',inset:0,background:'rgba(0,0,0,.5)',display:'grid',placeItems:'center',padding:18,zIndex:1000}}><div className="card" style={{width:'100%',maxWidth:620,maxHeight:'90vh',overflow:'auto',padding:22}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:18}}><h2>{title}</h2><button onClick={onClose} type="button" style={secondary}>✕</button></div>{children}</div></div>}
const input:React.CSSProperties={width:'100%',padding:'10px 11px',border:'1px solid var(--border-color)',borderRadius:8,background:'var(--bg-primary)',color:'var(--text-primary)'};
const primary:React.CSSProperties={padding:'10px 14px',borderRadius:8,background:'var(--accent)',color:'var(--accent-contrast)',fontWeight:650}; const secondary:React.CSSProperties={padding:'8px 10px',border:'1px solid var(--border-color)',borderRadius:8,background:'var(--bg-primary)',color:'var(--text-primary)'}; const danger:React.CSSProperties={...secondary,color:'var(--danger)'}; const two:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(200px,1fr))',gap:12}; const errorBox:React.CSSProperties={padding:12,color:'var(--danger)',border:'1px solid var(--danger)',borderRadius:8,marginBottom:16};
